name: Run Photoniq FaaS CLI

on: [workflow_dispatch]

jobs:
  run-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download Photoniq FaaS CLI
        run: curl -L -o faas-cli.tar.gz https://macrometacorp.github.io/photoniq-faas-cli-docs/faas-1.0.0-x86_64-unknown-linux-musl.tar.gz

      - name: Verify Downloaded File
        run: file faas-cli.tar.gz

      - name: Check File Size
        run: ls -lh faas-cli.tar.gz

      - name: Extract Photoniq FaaS CLI
        run: sudo tar -xzf faas-cli.tar.gz -C /usr/local/bin

      - name: Make CLI executable
        run: sudo chmod +x /usr/local/bin/faas-1.0.0-x86_64-unknown-linux-musl/faas

      - name: Run CLI and print output
        run: |
          echo "Running Photoniq FaaS CLI..."
          /usr/local/bin/faas-1.0.0-x86_64-unknown-linux-musl/faas remote deploy --nextjs
